  name: Release

  on:
    release:
      types: [published]

  jobs:
    build:
      strategy:
        matrix:
          goos: [linux]
          goarch: [amd64, arm64]
          include:
            - goos: linux
              goarch: arm
              goarm: 7
            - goos: linux
              goarch: arm
              goarm: 6
            - goos: linux
              goarch: arm
              goarm: 5
        fail-fast: false

      runs-on: ubuntu-24.04
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        GOARM: ${{ matrix.goarm }}
        CGO_ENABLED: 0

      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v5
          with:
            go-version: '1.24'

        - run: go mod download

        - name: Build
          run: |
            export _NAME=$(jq ".[\"$GOOS-$GOARCH$GOARM\"].friendlyName" -r < release/friendly-filenames.json)
            go build -tags "with_quic,with_utls" -v -o gg-$_NAME -trimpath -ldflags "-s -w -buildid=" .

        - name: Compress with UPX
          run: |
            curl -fsSL https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz -o /tmp/upx.tar.xz
            tar -xf /tmp/upx.tar.xz -C /tmp
            for f in gg-*; do /tmp/upx-4.2.4-amd64_linux/upx --best "$f"; done

        - name: Upload to Release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file_glob: true
            overwrite: true
            tag: ${{ github.ref }}
